"""User-supplied already published URLs. No outgoing Telegram operations."""
EVENTS = (
    ("https://bloomingbit.io/feed/news/121817", "이억원 금융위원장, 디지털자산 입법 속도·취약층 지원·부채 관리 병행", "사용자 확인 게시문(원문 검증 자료 아님): 이억원 금융위원장, 디지털자산 입법 속도·취약층 지원·부채 관리 병행"),
    ("https://bloomingbit.io/feed/news/121797", "CFTC 마이크 셀리그, 암호화폐에 기존 파생상품 증거금 모델 적용 입장", "사용자 확인 게시문(원문 검증 자료 아님): CFTC 마이크 셀리그, 암호화폐에 기존 파생상품 증거금 모델 적용 입장"),
    ("https://bloomingbit.io/feed/news/121790", "프렌치 힐, SEC CFTC 규칙만으로 부족…새 의회 전 클래리티 법안 통과 기대", "사용자 확인 게시문(원문 검증 자료 아님): 프렌치 힐, SEC CFTC 규칙만으로 부족…새 의회 전 클래리티 법안 통과 기대"),
    ("https://bloomingbit.io/feed/news/121780", "미국 재무부, 장기 국채 최대 60억달러 바이백", "사용자 확인 게시문(원문 검증 자료 아님): 미국 재무부, 장기 국채 최대 60억달러 바이백"),
    ("https://www.etoday.co.kr/news/view/2633689", "9월 FOMC 의사록 추가 인상 시사와 트럼프 금리 인하 압박", "사용자 확인 게시문(원문 검증 자료 아님): 9월 FOMC 의사록 추가 인상 시사와 트럼프 금리 인하 압박"),
    ("https://crypto.news/wells-fargo-talks-with-kraken-parent-about-crypto-trading/", "웰스파고, 크라켄 모회사와 암호화폐 거래 논의", "사용자 확인 게시문(원문 검증 자료 아님): 웰스파고, 크라켄 모회사와 암호화폐 거래 논의"),
    ("https://crypto.news/hashkey-bitgo-add-eth-and-sol-staking-for-institutions/", "해시키·비트고, 기관 ETH SOL 스테이킹 협력 확대", "사용자 확인 게시문(원문 검증 자료 아님): 해시키·비트고, 기관 ETH SOL 스테이킹 협력 확대"),
    ("https://bloomingbit.io/feed/news/121830", "토스·광주은행 스테이블코인 QR 결제 기술검증 완료", "사용자 확인 게시문(원문 검증 자료 아님): 토스·광주은행 스테이블코인 QR 결제 기술검증 완료"),
    ("https://x.com/cryptodotnews/status/2108082672010502429", "IMF, 엘살바도르 지급 승인과 추가 비트코인 축적 제한", "사용자 확인 게시문(원문 검증 자료 아님): IMF, 엘살바도르 지급 승인과 추가 비트코인 축적 제한"),
    ("https://bloomingbit.io/feed/news/121833", "그리스 디지털자산 10% 과세 추진, 연 500유로 면제", "사용자 확인 게시문(원문 검증 자료 아님): 그리스 디지털자산 10% 과세 추진, 연 500유로 면제"),
    ("https://bloomingbit.io/feed/news/121836", "스탠다드차타드 싱가포르 기관 디지털자산 수탁 출시 추진, 규제 조건·일정 미정", "사용자 확인 게시문(원문 검증 자료 아님): 스탠다드차타드 싱가포르 기관 디지털자산 수탁 출시 추진, 규제 조건·일정 미정"),
    ("https://bloomingbit.io/feed/news/121841", "삼성월렛 미국 USDC 송금 10월 마지막 주 계획, 외부 지갑 무료·은행 이체 수수료", "사용자 확인 게시문(원문 검증 자료 아님): 삼성월렛 미국 USDC 송금 10월 마지막 주 계획, 외부 지갑 무료·은행 이체 수수료"),
    ("https://www.tokenpost.kr/news/cryptocurrency/419934", "트라발라 AI 호텔 예약 출시, BNB 체인 USDT 결제 직접 승인", "사용자 확인 게시문(원문 검증 자료 아님): 트라발라 AI 호텔 예약 출시, BNB 체인 USDT 결제 직접 승인"),
    ("https://coingape.com/russia-moscow-exchange-plans-to-launch-crypto-trading-in-december/", "모스크바거래소 12월 암호화폐 거래 개시 계획", "사용자 확인 게시문(원문 검증 자료 아님): 모스크바거래소 12월 암호화폐 거래 개시 계획"),
    ("https://u.today/ripple-emerges-as-major-wall-street-threat", "리플프라임, 월가 은행과 레버리지 ETF 금융·중개 사업 경쟁 확대", "사용자 확인 게시문(원문 검증 자료 아님): 리플프라임, 월가 은행과 레버리지 ETF 금융·중개 사업 경쟁 확대"),
    ("https://bloomingbit.io/feed/news/121869", "JP모건 올해 암호화폐 시장 500억달러 유입과 4분기 모멘텀 보고", "사용자 확인 게시문(원문 검증 자료 아님): JP모건 올해 암호화폐 시장 500억달러 유입과 4분기 모멘텀 보고"),
    ("https://bloomingbit.io/feed/news/121861", "칼시 연준 10월 금리 동결 확률 84%", "사용자 확인 게시문(원문 검증 자료 아님): 칼시 연준 10월 금리 동결 확률 84%"),
    ("https://bloomingbit.io/feed/news/121881", "프랑스 스테이블코인 과세·손실 10년 공제·국외전출세 추진", "사용자 확인 게시문(원문 검증 자료 아님): 프랑스 스테이블코인 과세·손실 10년 공제·국외전출세 추진"),
    ("https://timestabloid.com/evernoths-corporate-strategy-for-xrp-you-need-to-see/", "에버노스 XRP 축적·일본 한국 진출·기관 대출 DeFi 운용 전략", "사용자 확인 게시문(원문 검증 자료 아님): 에버노스 XRP 축적·일본 한국 진출·기관 대출 DeFi 운용 전략"),
    ("https://x.com/cryptodotnews/status/2108384454175502685", "마스터카드 멕시코 암호화폐 연동 카드 출시·결제 시 법정화폐 전환", "사용자 확인 게시문(원문 검증 자료 아님): 마스터카드 멕시코 암호화폐 연동 카드 출시·결제 시 법정화폐 전환"),
    ("https://crypto.news/president-trump-unveils-215m-quantum-computing-plan/", "트럼프 2억1500만달러 양자컴퓨팅 계획 발표", "사용자 확인 게시문(원문 검증 자료 아님): 트럼프 2억1500만달러 양자컴퓨팅 계획 발표"),
    ("https://bloomingbit.io/feed/news/121890", "저스틴 선, 2012년 전재산 암호화폐 전환 회고 발언", "사용자 확인 게시문(원문 검증 자료 아님): 저스틴 선, 2012년 전재산 암호화폐 전환 회고 발언"),
    ("https://x.com/cryptodotnews/status/2108466329556566260", "XRP레저 은행·스테이블코인·토큰화 펀드 권한 위임 도구 추가", "사용자 확인 게시문(원문 검증 자료 아님): XRP레저 은행·스테이블코인·토큰화 펀드 권한 위임 도구 추가"),
    ("https://coingape.com/robinhood-crypto-explores-new-product-with-1-9t-aum-t-rowe-price/", "로빈후드·티로우프라이스 액티브 ETF 연계 토큰 상품 검토", "사용자 확인 게시문(원문 검증 자료 아님): 로빈후드·티로우프라이스 액티브 ETF 연계 토큰 상품 검토"),
    ("https://bloomingbit.io/feed/news/121876", "아서 헤이즈, 강세장과 향후 통화공급 확대에 대한 전망 발언", "사용자 확인 게시문(원문 검증 자료 아님): 아서 헤이즈, 강세장과 향후 통화공급 확대에 대한 전망 발언"),
    ("https://coingape.com/mara-holdings-dumps-996-btc-during-1-billion-in-crypto-market-liquidations/", "MARA 996 BTC 갤럭시디지털 이동, 매도 추정 보도·매도 확정 아님", "사용자 확인 게시문(원문 검증 자료 아님): MARA 996 BTC 갤럭시디지털 이동, 매도 추정 보도·매도 확정 아님"),
    ("https://www.theblock.co/news/business/2026-10-09-ledger-cryptobilis-fund-losses-418163", "레저 CryptoBilis 유출 조사·판매 배송 중단 요청, 공급망 공격 추정 단계", "사용자 확인 게시문(원문 검증 자료 아님): 레저 CryptoBilis 유출 조사·판매 배송 중단 요청, 공급망 공격 추정 단계"),
    ("https://www.theblock.co/news/defi/2026-10-09-tokenization-supercycle-base-jesse-pollak-418144", "제시 폴락, 주식 토큰화·비달러 스테이블코인 슈퍼사이클 전망", "사용자 확인 게시문(원문 검증 자료 아님): 제시 폴락, 주식 토큰화·비달러 스테이블코인 슈퍼사이클 전망"),
    ("https://coingape.com/blockchain-com-pushes-for-prediction-markets-and-crypto-derivatives-trading-in-the-us/", "블록체인닷컴 미국 예측시장·암호화폐 파생상품 CFTC 등록 추진", "사용자 확인 게시문(원문 검증 자료 아님): 블록체인닷컴 미국 예측시장·암호화폐 파생상품 CFTC 등록 추진"),
    ("https://coingape.com/ripple-chairman-democratic-megadonor-chris-larsen-donated-22-5m-us-fec/", "크리스 라센 미국 연방 후보·슈퍼PAC 최소 2250만달러 기부", "사용자 확인 게시문(원문 검증 자료 아님): 크리스 라센 미국 연방 후보·슈퍼PAC 최소 2250만달러 기부"),
    ("https://bloomingbit.io/feed/news/121930", "미 법무부 바이낸스 43억달러 합의 이행·자금세탁방지 준수 조사", "사용자 확인 게시문(원문 검증 자료 아님): 미 법무부 바이낸스 43억달러 합의 이행·자금세탁방지 준수 조사"),
    ("https://bloomingbit.io/feed/news/121912", "앤드루 쿠오모 토큰화 주식이 시장을 변화시킬 것이라는 발언", "사용자 확인 게시문(원문 검증 자료 아님): 앤드루 쿠오모 토큰화 주식이 시장을 변화시킬 것이라는 발언"),
    ("https://www.tokenpost.kr/news/cryptocurrency/420766", "아크·문페이 연동, 카드·애플페이·구글페이·은행송금 구매 USDC 아크 전송", "사용자 확인 게시문(원문 검증 자료 아님): 아크·문페이 연동, 카드·애플페이·구글페이·은행송금 구매 USDC 아크 전송"),
    ("https://bloomingbit.io/feed/news/121931", "에버노스 4억7300만 XRP 보유, SPAC 합병 완료·12일 나스닥 거래 예정", "사용자 확인 게시문(원문 검증 자료 아님): 에버노스 4억7300만 XRP 보유, SPAC 합병 완료·12일 나스닥 거래 예정"),
    ("https://bloomingbit.io/feed/news/121932", "베센트 이번 주 이란 연계 암호화폐 10억달러 압류 계획 발언", "사용자 확인 게시문(원문 검증 자료 아님): 베센트 이번 주 이란 연계 암호화폐 10억달러 압류 계획 발언"),
    ("https://timestabloid.com/imf-highlights-xrp-and-xlm-in-recent-report-heres-why/", "IMF 토큰화 금융시장 보고서 XRPL 스텔라 포함", "사용자 확인 게시문(원문 검증 자료 아님): IMF 토큰화 금융시장 보고서 XRPL 스텔라 포함"),
    ("https://timestabloid.com/ripple-xrp-makes-big-move-right-before-the-dtcc-launches/", "리플 수탁 칸톤 통합 완료, DTCC 토큰화 서비스 예정", "사용자 확인 게시문(원문 검증 자료 아님): 리플 수탁 칸톤 통합 완료, DTCC 토큰화 서비스 예정"),
    ("https://x.com/cryptodotnews/status/2108731742509236437", "스텔라 20개 이상 다국적 기업 급여 지급·머니그램 USDC 현금화 지원", "사용자 확인 게시문(원문 검증 자료 아님): 스텔라 20개 이상 다국적 기업 급여 지급·머니그램 USDC 현금화 지원"),
)
URLS = (
    "https://bloomingbit.io/feed/news/121817",
    "https://bloomingbit.io/feed/news/121797",
    "https://bloomingbit.io/feed/news/121790",
    "https://bloomingbit.io/feed/news/121780",
    "https://www.etoday.co.kr/news/view/2633689",
    "https://crypto.news/wells-fargo-talks-with-kraken-parent-about-crypto-trading/",
    "https://crypto.news/hashkey-bitgo-add-eth-and-sol-staking-for-institutions/",
    "https://bloomingbit.io/feed/news/121830",
    "https://x.com/cryptodotnews/status/2108082672010502429",
    "https://bloomingbit.io/feed/news/121833",
    "https://bloomingbit.io/feed/news/121836",
    "https://bloomingbit.io/feed/news/121841",
    "https://www.tokenpost.kr/news/cryptocurrency/419934",
    "https://coingape.com/russia-moscow-exchange-plans-to-launch-crypto-trading-in-december/",
    "https://u.today/ripple-emerges-as-major-wall-street-threat",
    "https://bloomingbit.io/feed/news/121869",
    "https://bloomingbit.io/feed/news/121861",
    "https://bloomingbit.io/feed/news/121881",
    "https://timestabloid.com/evernoths-corporate-strategy-for-xrp-you-need-to-see/",
    "https://x.com/cryptodotnews/status/2108384454175502685",
    "https://crypto.news/president-trump-unveils-215m-quantum-computing-plan/",
    "https://bloomingbit.io/feed/news/121890",
    "https://x.com/cryptodotnews/status/2108466329556566260",
    "https://coingape.com/robinhood-crypto-explores-new-product-with-1-9t-aum-t-rowe-price/",
    "https://bloomingbit.io/feed/news/121876",
    "https://coingape.com/mara-holdings-dumps-996-btc-during-1-billion-in-crypto-market-liquidations/",
    "https://www.theblock.co/news/business/2026-10-09-ledger-cryptobilis-fund-losses-418163",
    "https://www.theblock.co/news/defi/2026-10-09-tokenization-supercycle-base-jesse-pollak-418144",
    "https://coingape.com/blockchain-com-pushes-for-prediction-markets-and-crypto-derivatives-trading-in-the-us/",
    "https://coingape.com/ripple-chairman-democratic-megadonor-chris-larsen-donated-22-5m-us-fec/",
    "https://bloomingbit.io/feed/news/121930",
    "https://bloomingbit.io/feed/news/121912",
    "https://www.tokenpost.kr/news/cryptocurrency/420766",
    "https://bloomingbit.io/feed/news/121931",
    "https://bloomingbit.io/feed/news/121932",
    "https://timestabloid.com/imf-highlights-xrp-and-xlm-in-recent-report-heres-why/",
    "https://timestabloid.com/ripple-xrp-makes-big-move-right-before-the-dtcc-launches/",
    "https://x.com/cryptodotnews/status/2108731742509236437",
)
